name: Validate, build and deploy to Maven Central
on:
  push:
    branches:
      - main

jobs:
  maven-build-and-release:
    if: "!contains(github.event.head_commit.message, '[skip-release]')"
    uses: entur/gha-maven-central/.github/workflows/maven-publish.yml@main
    secrets: inherit
    with:
      next_version: minor
      version_strategy: tag
      version_tag_prefix: release-
